### ISSUE TITLE
Transifex is broken

### ISSUE THREAD

**Issue by locness3** [ScratchUtilities/gobo.icu#100]
Hi! It seems like there isn't an active Transifex plan for the organization, when I try to do anything I get errors like these :
![Screen Shot 2020-04-10 at 13 00 17](https://user-images.githubusercontent.com/37651007/78986323-56e6d500-7b2b-11ea-836b-93449bc52952.png)
![Screen Shot 2020-04-10 at 13 00 44](https://user-images.githubusercontent.com/37651007/78986334-5b12f280-7b2b-11ea-8e59-5726320719ec.png)
@KennethSweezy

**Comment by KennethSweezy** [comment]
This is because the plan we are on, there are a maximum of ten translators
in the project. I had to manually cycle translators for when they wanted to
translate. If you would like to work on tranlations I can rotate some
people out.

**Comment by locness3** [comment]
No, thanks. But whaty plan are you using ? the open-source one?

**Comment by KennethSweezy** [comment]
I am using the one that Transifex provides in the GitHub education pack. I
can't remember exactly what plan it is though.

**Comment by locness3** [comment]
I guess it's the starter one.

**Comment by KennethSweezy** [comment]
Considering that the project has been translated into 15 languages (plus English) I am going to discontinue the translation portion of this project. The total number of people on Earth that could comfortably read and use Gobo.icu is almost **4 billion**. There are some gaps in our translations (we don't have translations for Mandarin) but we do have translations for 4 of the 5 most spoken languages.

Thank you to all contributors.

**Comment by locness3** [comment]
wait, it's gobo.icu now?

**Comment by KennethSweezy** [comment]
Yes.
