### ISSUE TITLE
gobo.cf redirects to a website that is not safe for work

### ISSUE THREAD

**Issue by ICTman1076** [ScratchUtilities/gobo.icu#84]
**Describe the bug**
Title says it all. For the target audience of this website, this is a big problem.

**To Reproduce**
1. Go to `gobo.cf`
2. Quickly close the tab before someone else sees

**Expected behavior**
To see the real gobo.cf site

**Additional context**
iirc .cf is a freenom domain. If you got it for free, chances are you surpassed your visitor limit (yes there is one, no they don't make it clear enough) and so they de-registered it, making new registrants pay for it. Thing is, someone *else* could also pay for it and hijack your visitors. You may need to contact freenom directly about this.

**Comment by ICTman1076** [comment]
If you need something free to replace it, https://freedns.afraid.org can be quite good. Can't use cloudflare on it though - just A records.

**Comment by brunopulis** [comment]
Same issue here.

**Comment by KennethSweezy** [comment]
Yes, this is currently a big issue. I am attempting to work with Freenom on this issue.

**Comment by ICTman1076** [comment]
Wish ya the best of luck. 

I'd like to suggest a couple of things:
[ ] Updating the README to tell people not to visit gobo.cf
[ ] Changing it so that the github.io page doesn't redirect to gobo.cf (maybe even works in place of it)

**Comment by KennethSweezy** [comment]
@ICTman1076 If you would like to get a PR for Hacktoberfest I will accept it.

**Comment by IamTregsthedev** [comment]
I have fixed this promblem for the time being both in the master repo and made a clone

https://gobo.glitch.me/home/

The glitch works, as the same as this repo, also has all the translations

**Comment by IamTregsthedev** [comment]
> I have fixed this promblem for the time being both in the master repo and made a clone
> 
> https://gobo.glitch.me/home/
> 
> The glitch works, as the same as this repo, also has all the translations

I have just noticed that it was already done, but the website seems to be having some promblems with the images.

The Glitch Site works perfecly fine, and it would be nice if we used for now. We can have custom domains onn Glitch.me

**Comment by DeleteThisAcount** [comment]
> > I have fixed this promblem for the time being both in the master repo and made a clone
> > https://gobo.glitch.me/home/
> > The glitch works, as the same as this repo, also has all the translations
> 
> I have just noticed that it was already done, but the website seems to be having some promblems with the images.
> 
> The Glitch Site works perfecly fine, and it would be nice if we used for now. We can have custom domains onn Glitch.me

glitch has to wake up sometimes, making this even slower then just visiting the page anyways.

**Comment by ICTman1076** [comment]
> We can have custom domains onn Glitch.me

We can have custom domain on GitHub too, but that's no use since it appears that the maintainers have lost access to gobo.cf altogether

**Comment by IamTregsthedev** [comment]
> > We can have custom domains onn Glitch.me
> 
> ****We can have custom domain on GitHub too, but that's no use since it appears that the maintainers have lost access to gobo.cf altogether.****

I know. I've been Thinking about switching our site to glitch, I'm not sure why. We need the domain back or Something Shorter.

We could use a Another Scratch Spirte Name like Tera Maybe?

@KennethSweezy  Have you emailed or contancted Freenom? I feel it might into the best insterest of finding a new domain or either Purchasing a Domain.

**Comment by IamTregsthedev** [comment]
> > > I have fixed this promblem for the time being both in the master repo and made a clone
> > > https://gobo.glitch.me/home/
> > > The glitch works, as the same as this repo, also has all the translations
> > 
> > 
> > I have just noticed that it was already done, but the website seems to be having some promblems with the images.
> > The Glitch Site works perfecly fine, and it would be nice if we used for now. We can have custom domains onn Glitch.me
> 
> glitch has to wake up sometimes, making this even slower then just visiting the page anyways.

I didn't know about that. Glitch Doesn't seem to slow or wake up slowly sometimes. 
 In #97, We're looking for a new Domain, I think Glitch Isn't a option. I forked the repo Once Again Just in case.

**Comment by KennethSweezy** [comment]
Closed 
See [#97](https://github.com/ScratchUtilities/gobo.icu/issues/97#issuecomment-633666742) for details.
