### ISSUE TITLE
Premium Domain

### ISSUE THREAD

**Issue by DeleteThisAcount** [ScratchUtilities/gobo.icu#97]
Currently gobo.cf is not really what people want to see. That's probably because it's a cheap/free domain, freenom likes to give away domains for the highest bidder. 

This might sound crazy, but possibly renaming gobo.cf to something with a premium domain?

There are some great ones on google domains (not available everywhere), but gobo.army sounds amazing to me.

Gobo.fyi is nice
Gobo.dev is great

**Comment by KennethSweezy** [comment]
While I do agree that we should switch domains, I would much prefer a two-letter TLD (.us, .co, .cc, etc) instead of a three- or four-letter TLD (.com, .dev, .fyi, .army, etc).

**Comment by KennethSweezy** [comment]
I can try and get us one of the ones on [this list](https://opendomain.org/free-domains/). I would like to see which one everyone prefers first though.

cc @Andreto

**Comment by chexbox** [comment]
gobo.co might be good. I really don't know at this point, though.

**Comment by KennethSweezy** [comment]
I will update the list of possible options in this comment:
Below are through internet.bs:
- gobo.li
- gobo.tf
- gobo.re
- gobo.pm
- gobo.yt
- gobo.wf
- gobo.vg

**Comment by DeleteThisAcount** [comment]
gobo.pm sounds nice, gobo.co sounds cool aswell

**Comment by IamTregsthedev** [comment]
> I can try and get us one of the ones on [this list](https://opendomain.org/free-domains/). I would like to see which one everyone prefers first though.
> 
> cc @Andreto
> 
> I was thinking linq.org because we will be linking things together.

Sounds nice, Although Something like gobo.vg gobo.pm gobo.il would work

**Comment by IamTregsthedev** [comment]
gobo.tk | Not available
gobo.ml | Not available
gobo.ga | Not available
gobo.cf | Not available
gobo.gq | Not available

They've also Removed all the Free Extestions for Gobo. Either Someone Took from us or Freenom Cheated us out.

They Have a Vistor limit, Freenom Just Seems Dirty a Bit. It kinda makes sense, You're getting  fre domain. .tk Domains on Godadday sell like for $2-6 Dollers or more on other Platforms.

**Comment by IamTregsthedev** [comment]
> I will update the list of possible options in this comment:
> Below are through internet.bs:
> 
> * gobo.li
> * gobo.tf
> * gobo.re
> * gobo.pm
> * gobo.yt
> * gobo.wf
> * gobo.vg


Gobo.wf and .tf sounds nice

**Comment by ICTman1076** [comment]
If we're buying a new domain I suggest you look at https://tld-list.com for the best prices, however I do not recommend OVH (their customer support is terrible and they have problems frequently)

**Comment by ICTman1076** [comment]
> 
> 
> I can try and get us one of the ones on [this list](https://opendomain.org/free-domains/). I would like to see which one everyone prefers first though.
> 
> cc @Andreto
> 
> I was thinking linq.org because we will be linking things together.

You should then also look at [afraid.org](https://freedns.afraid.org) - they have LOADS of domains you can use

**Comment by KennethSweezy** [comment]
# New Domain
I have acquired ``gobo.icu`` for the project. This has lead to the renaming of the project from ``gobo.cf`` to ``gobo.icu``.

@ScratchUtilities/core-devs @chexbox @IamTregsthedev @DeleteThisAcount @ICTman1076

**Comment by IamTregsthedev** [comment]
Great, why icu?

**Comment by KennethSweezy** [comment]
@IamTregsthedev It was one of the only domains that had gobo available that provided Whois privacy.

**Comment by JeffaloBob** [comment]
![image](https://user-images.githubusercontent.com/40470736/82904093-41eec580-9f62-11ea-99ff-5cf50faa19de.png)
